version: '3.8'

services:
  php-8.2:
    &php
    working_dir: /app
    volumes:
      - .:/app
    build:
      args:
        PHP_VERSION: "8.2"
        PHP_XDEBUG_VERSION: "3.2.2"
  php-8.3:
    <<: *php
    build:
      args:
        PHP_VERSION: "8.3"
        PHP_XDEBUG_VERSION: "3.3.1"